workspace 'Examples.xcworkspace'
platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

post_install do |installer|
   installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      end
   end
end

abstract_target 'Example' do
  pod 'SwiftUIReactorKit', :path => '../'
  pod 'ReactorKit', '~> 3.0'

  target 'Counter' do
    project 'Counter/Counter.xcodeproj'
  end
end
